### ISSUE TITLE
[MCL65+] SN74LVC573AN substitute?

### ISSUE THREAD

**Issue by aleksander-martin** [MicroCoreLabs/Projects#12]
Can SN74LVC573AN be replaced by other series? On the schematics is written 74LS573, but I am not sure will it work?

**Comment by MicroCoreLabs** [comment]
The pinouts are different so they are not interchangeable.  If you change the schematics and layout then you can use a '373.
________________________________
From: Aleksander ***@***.***>
Sent: Monday, February 6, 2023 10:21 AM
To: MicroCoreLabs/Projects ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicroCoreLabs/Projects] [MCL65+] SN74LVC573AN substitute? (Issue #12)


Can SN74LVC573AN be replaced by other series? On the schematics is written 74LS573, but I am not sure will it work?

**Comment by aleksander-martin** [comment]
Well, I didn't want to replace 573 with 373. I just want to replace LVC with LS (or any other). Pinout for all 573 is the same in all series :)

**Comment by MicroCoreLabs** [comment]
Ah I see..  Any logic family which has 5V tolerant inputs and 3.3V outputs will work fine.
________________________________

**Comment by aleksander-martin** [comment]
Thank you very much :)

**Comment by AWCharlie** [comment]
HCT should work.
