### ISSUE TITLE
M68K - Infinite loop in test all opcodes

### ISSUE THREAD

**Issue by xahon** [MicroCoreLabs/Projects#13]
I have an endless loop in this part of code

![image](https://user-images.githubusercontent.com/18731681/217913386-1715e96c-7b41-49d3-ab9b-c97e2d9364fd.png)

lines 3898-3916
https://github.com/MicroCoreLabs/Projects/blob/ea66a81165a3f88b8d14fafd05a566c4d131c5ae/MCL68/MC68000_Test_Code/MC68000_test_all_opcodes.X68#L3898-L3916

Easy68k v5.16.1

**Comment by MicroCoreLabs** [comment]
It seems like is running forever, but it is just running many iterations.  If you run in Easy68K you will see it gets past this code and is not an infinite loop.

**Comment by xahon** [comment]
You are right. It takes a lot of patience to finish the program. I accidentally forgot to turn off the simulation for a night and now it's infinitely loops in ALL_DONE branch
