### ISSUE TITLE
40 pin dip breakout for MCL65 ?

### ISSUE THREAD

**Issue by drudru** [MicroCoreLabs/Projects#19]
Hi, did you buy or make the 40 pin dip breakout that you would connect the jumper wires with?
Just to be clear, this is the board that you inserted into the motherboard 40 pin dip sockets.

**Comment by MicroCoreLabs** [comment]
Yes, I developed this small PCB and the files are also on GitHub.  Yes, you can plug this board into the motherboard, replacing the original 6502.
________________________________
From: Dru Nelson ***@***.***>
Sent: Wednesday, May 24, 2023 9:55 AM
To: MicroCoreLabs/Projects ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicroCoreLabs/Projects] 40 pin dip breakout for MCL65 ? (Issue #19)


Hi, did you buy or make the 40 pin dip breakout that you would connect the jumper wires with?
Just to be clear, this is the board that you inserted into the motherboard 40 pin dip sockets.

**Comment by drudru** [comment]
Sorry to ask, but which dir has the files for this pcb?

**Comment by MicroCoreLabs** [comment]
Oh sorry, you are referring to the MCL65 project, not the MCL65+ 🙂

I never made any PCB for this.. I just hand-wired and soldered my own little converter from the FPGA board to the 40-pin DIP.
________________________________

**Comment by drudru** [comment]
Ah, that makes sense. I wasn't quite sure from the photos.
Thank you.
