### ISSUE TITLE
MCL65 core appears to be missing ROM_2Kx32.v

### ISSUE THREAD

**Issue by orange808** [MicroCoreLabs/Projects#3]
Having trouble compiling this core.  I cannot locate the ROM_2Kx32 module.

**Comment by MicroCoreLabs** [comment]
It is a generic 2Kx32 ROM block for the microcode which you can target to your FPGA technology.
________________________________

**Comment by orange808** [comment]
That makes sense.  Even if you had posted a file, I would still have needed to edit it.

Thanks for the reply.  We can close this one.
